//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Org_Services
    {
        public int id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> org_id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Services_ Services_ { get; set; }
        public virtual organization organization { get; set; }
        public virtual user user { get; set; }
    }
}
