//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public string msg { get; set; }
        public string replay { get; set; }
        public string type { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> from { get; set; }
        public Nullable<int> to { get; set; }
        public Nullable<int> emp_id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
