//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QueueSystemDBWeb1 : DbContext
    {
        public QueueSystemDBWeb1()
            : base("name=QueueSystemDBWeb1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointments_> Appointments_ { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Doc> Doc { get; set; }
        public virtual DbSet<Emp_Org_Services> Emp_Org_Services { get; set; }
        public virtual DbSet<Job_title_> Job_title_ { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<organization> organization { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Request_attachement> Request_attachement { get; set; }
        public virtual DbSet<Requirments_Doc> Requirments_Doc { get; set; }
        public virtual DbSet<Services_> Services_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
