//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string msg { get; set; }
        public Nullable<bool> seen { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string type_noti { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> type_noti_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
