//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_attachement
    {
        public int id { get; set; }
        public string path { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<int> Requried_id { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Requirments_Doc Requirments_Doc { get; set; }
    }
}
