//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirments_Doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirments_Doc()
        {
            this.Request_attachement = new HashSet<Request_attachement>();
        }
    
        public int id { get; set; }
        public string notes { get; set; }
        public Nullable<int> Service_id { get; set; }
        public Nullable<int> doc_id { get; set; }
    
        public virtual Doc Doc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_attachement> Request_attachement { get; set; }
        public virtual Services_ Services_ { get; set; }
    }
}
