//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services_()
        {
            this.Appointments_ = new HashSet<Appointments_>();
            this.Emp_Org_Services = new HashSet<Emp_Org_Services>();
            this.Request = new HashSet<Request>();
            this.Requirments_Doc = new HashSet<Requirments_Doc>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.TimeSpan> starttime { get; set; }
        public Nullable<System.TimeSpan> endtime { get; set; }
        public Nullable<int> NumOfEmp { get; set; }
        public Nullable<System.TimeSpan> period { get; set; }
        public Nullable<System.TimeSpan> breakStart { get; set; }
        public Nullable<System.TimeSpan> breakPeriod { get; set; }
        public Nullable<int> org_id { get; set; }
        public Nullable<int> toFinish { get; set; }
        public Nullable<int> toExpire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments_> Appointments_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Org_Services> Emp_Org_Services { get; set; }
        public virtual organization organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirments_Doc> Requirments_Doc { get; set; }
    }
}
